// <auto-generated />
using System;
using Immo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Immo.Data.Migrations
{
    [DbContext(typeof(ImmoContext))]
    [Migration("20260619154035_urlTemplate")]
    partial class urlTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Immo.Data.Entities.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgencyDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiListingUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CrawlRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaginationSelector")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("Immo.Data.Entities.AgencyListingCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlPosibilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("AgencyListingChecks");
                });

            modelBuilder.Entity("Immo.Data.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrawlIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NewOrUpdatedThresholdDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredTimezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecrawlAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnderOptionKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CrawlIntervalHours = 4,
                            FromEmail = "",
                            NewOrUpdatedThresholdDays = 7,
                            PreferredTimezone = "UTC",
                            RecrawlAfterDays = 3,
                            SmtpHost = "",
                            SmtpPassword = "",
                            SmtpPort = 25,
                            SmtpUseSsl = true,
                            SmtpUsername = "",
                            SoldKeywords = "verkocht,sold",
                            UnderOptionKeywords = "onder optie,optie"
                        });
                });

            modelBuilder.Entity("Immo.Data.Entities.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Immo.Data.Entities.ParserConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressSelector")
                        .HasColumnType("TEXT");

                    b.Property<int>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BedroomLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("BedroomSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityLabel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CountBedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpcLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalIdPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonArrayPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonBedroomsPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonCityPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonDescriptionPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonDetailUrlTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonEpcPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonExternalIdPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonLivingAreaPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPlotAreaPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPricePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonSoldValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonStatusPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonTitlePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonUnderOptionValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonUrlPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonZipCodePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("LivingAreaLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlotAreaLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecContainerSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecLabelSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecValueSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCodeLabel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId")
                        .IsUnique();

                    b.ToTable("ParserConfigs");
                });

            modelBuilder.Entity("Immo.Data.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpcScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LivingArea")
                        .HasColumnType("REAL");

                    b.Property<double?>("PlotArea")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("RawPageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UnderOption")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Immo.Data.Entities.PropertyHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyHistories");
                });

            modelBuilder.Entity("Immo.Data.Entities.RawPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CrawledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsParsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("RawPages");
                });

            modelBuilder.Entity("Immo.Data.Entities.AgencyListingCheck", b =>
                {
                    b.HasOne("Immo.Data.Entities.Agency", "Agency")
                        .WithMany("AgencyListingChecks")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Immo.Data.Entities.ParserConfig", b =>
                {
                    b.HasOne("Immo.Data.Entities.Agency", "Agency")
                        .WithOne("ParserConfig")
                        .HasForeignKey("Immo.Data.Entities.ParserConfig", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Immo.Data.Entities.Property", b =>
                {
                    b.HasOne("Immo.Data.Entities.Agency", "Agency")
                        .WithMany("Properties")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Immo.Data.Entities.PropertyHistory", b =>
                {
                    b.HasOne("Immo.Data.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Immo.Data.Entities.RawPage", b =>
                {
                    b.HasOne("Immo.Data.Entities.Agency", "Agency")
                        .WithMany("RawPages")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Immo.Data.Entities.Agency", b =>
                {
                    b.Navigation("AgencyListingChecks");

                    b.Navigation("ParserConfig");

                    b.Navigation("Properties");

                    b.Navigation("RawPages");
                });
#pragma warning restore 612, 618
        }
    }
}
