// <auto-generated />
using System;
using Immo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Immo.Data.Migrations
{
    [DbContext(typeof(ImmoContext))]
    partial class ImmoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Immo.Data.Entities.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgencyDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaginationSelector")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("Immo.Data.Entities.AgencyListingCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlPosibilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("AgencyListingChecks");
                });

            modelBuilder.Entity("Immo.Data.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecrawlAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoldKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnderOptionKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RecrawlAfterDays = 3,
                            SoldKeywords = "verkocht,sold",
                            UnderOptionKeywords = "onder optie,optie"
                        });
                });

            modelBuilder.Entity("Immo.Data.Entities.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Immo.Data.Entities.ParserConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressSelector")
                        .HasColumnType("TEXT");

                    b.Property<int>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BedroomLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("BedroomSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityLabel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CountBedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpcLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalIdPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("LivingAreaLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlotAreaLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceSelector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecContainerSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecLabelSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecValueSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleSelector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCodeLabel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId")
                        .IsUnique();

                    b.ToTable("ParserConfigs");
                });

            modelBuilder.Entity("Immo.Data.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpcScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LivingArea")
                        .HasColumnType("REAL");

                    b.Property<double?>("PlotArea")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("RawPageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UnderOption")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Immo.Data.Entities.RawPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CrawledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsParsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RawPages");
                });

            modelBuilder.Entity("Immo.Data.Entities.AgencyListingCheck", b =>
                {
                    b.HasOne("Immo.Data.Entities.Agency", "Agency")
                        .WithMany("AgencyListingChecks")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Immo.Data.Entities.ParserConfig", b =>
                {
                    b.HasOne("Immo.Data.Entities.Agency", "Agency")
                        .WithOne("ParserConfig")
                        .HasForeignKey("Immo.Data.Entities.ParserConfig", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Immo.Data.Entities.Agency", b =>
                {
                    b.Navigation("AgencyListingChecks");

                    b.Navigation("ParserConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
